server:
   port: 8971
  
spring: 
   application: 
      name: secure-rest-api
   datasource: 
      url:  jdbc:mysql://localhost:3306/secure_restdb
      username: root
      password: Tiger2143@+%
   jpa: 
      show-sql: true
      hibernate: 
         ddl-auto: create
      properties: 
         hibernate:
            format_sql: true

